#!/usr/bin/env python3
"""
ELT365 Lesson Publisher — Months 6-7 + Specialist Extensions
Posts 61 micro-lessons (D152-D212) as drafts to sourovdeb.com.
Endpoint: https://sourovdeb.com/wp-json/sourov/v1/ai-post

Usage:
    python3 post_elt365_m06_m07.py

Requires: Python 3.6+ (stdlib only, no third-party packages)
"""

import json
import urllib.request
import urllib.error
import time
import sys

WP_ENDPOINT = 'https://sourovdeb.com/wp-json/sourov/v1/ai-post'
WP_KEY = '0767044896thevenet_'
DISCLAIMER = (
    '<p><em>Independent project; not affiliated with, endorsed by, or accredited '
    'by Cambridge University Press &amp; Assessment. Confers no qualification.</em></p>'
)


def make_html(idea, example, try_task):
    return (
        '<p><strong>Idea &#8212;</strong> ' + idea + '</p>'
        '<p><strong>Example &#8212;</strong> ' + example + '</p>'
        '<p><strong>Try &#8212;</strong> ' + try_task + '</p>'
        + DISCLAIMER
    )


def wp_post(post):
    data = json.dumps(post).encode('utf-8')
    req = urllib.request.Request(
        WP_ENDPOINT,
        data=data,
        headers={
            'X-Sourov-Key': WP_KEY,
            'Content-Type': 'application/json',
        },
        method='POST',
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.getcode(), resp.read().decode('utf-8')
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode('utf-8')
    except Exception as e:
        return 0, str(e)


BASE_TAGS = 'ELT365, teacher training, ELT'
REC_TAGS  = BASE_TAGS + ', receptive skills'
LIST_TAGS = BASE_TAGS + ', receptive skills, listening'
READ_TAGS = BASE_TAGS + ', receptive skills, reading'
PRO_TAGS  = BASE_TAGS + ', productive skills'
SPK_TAGS  = BASE_TAGS + ', productive skills, speaking'
WRT_TAGS  = BASE_TAGS + ', productive skills, writing'
YL_TAGS   = BASE_TAGS + ', young learners, teaching kids, EYL'
BE_TAGS   = BASE_TAGS + ', business English, ESP, professional English'
MA_TAGS   = BASE_TAGS + ', mixed ability, differentiation, inclusive teaching'
ERR_TAGS  = BASE_TAGS + ', error correction, feedback'


def lesson(day, title, idea, example, try_task, tags, meta):
    padded = str(day).zfill(3)
    full_title = f'ELT365 · Day {padded} — {title}'
    seo_title  = f'ELT365 · Day {padded} — {title} | Sourov Deb'
    return {
        'title':            full_title,
        'content':          make_html(idea, example, try_task),
        'status':           'draft',
        'category':         'English Teaching',
        'tags':             tags,
        'meta_description': meta[:155],
        'seo_title':        seo_title,
    }


LESSONS = [
    # MONTH 6: RECEPTIVE SKILLS (D152-D181)
    lesson(152,'Why listening is harder than it looks','Listening in a second language demands simultaneous decoding of sound, parsing of grammar, and construction of meaning — all in real time, with no rewind button.','A learner who reads <em>I should have gone</em> easily may miss it in speech as /aɪ ʃədəv gɒn/ — four words compressed into a blur.','Record yourself saying three natural phrases. Play them back. How much did you compress?',LIST_TAGS,'Why second-language listening is cognitively demanding, and what teachers can do to reduce the load.'),
    lesson(153,'Bottom-up vs top-down listening','Bottom-up processing builds meaning from individual sounds upward; top-down uses prior knowledge and context to predict. Skilled listeners use both simultaneously.','Hearing a weather forecast, you already expect “temperature”, “rain”, “degrees” — top-down. Catching the actual number spoken is bottom-up.','Ask a learner to predict five words before playing a short news clip. Which predictions were right?',LIST_TAGS,'How bottom-up and top-down processing work in listening, with a classroom prediction task to develop both.'),
    lesson(154,'Gist tasks — one question, whole text','A gist task poses one global question answered by hearing the whole text. It prevents learners from switching off once they catch a single familiar word.','\'What is the main topic of this conversation?\' is a gist task. \'What time does the train leave?\' is a detail task — do not start there.','Write one gist question for a two-minute audio clip you use in class.',LIST_TAGS,'What gist tasks are, why they come first in a listening lesson, and how to write one.'),
    lesson(155,'Listening for detail','Detail tasks ask learners to extract specific information. Set them after the gist task; front-loading detail questions causes panic and learners miss everything.','\'Which city does the speaker prefer?\' or \'How much does the flight cost?\' — one answer, locatable in the text.','Write three detail questions at different difficulty levels for the same listening text.',LIST_TAGS,'How to sequence detail tasks after gist work in a listening lesson, with three difficulty levels explained.'),
    lesson(156,'Predicting before you listen','Prediction activates schema, focuses attention, and gives learners a genuine reason to listen. It is the most underused pre-listening technique.','Show a photo of a busy airport and ask \'What might these people be talking about?\' before playing a dialogue set there.','Write one prediction task for a listening text you teach this week.',LIST_TAGS,'Why prediction tasks are the most underused pre-listening activity and how to write one in two minutes.'),
    lesson(157,'Schema theory in listening','Schema are mental frameworks built from experience. Learners with relevant cultural schema comprehend far more, even at lower language levels.','A learner who has visited a doctor understands a medical dialogue more easily — even without all the vocabulary — because the script is familiar.','Identify one listening text where cultural knowledge gives native speakers an unfair advantage. Adjust your lead-in to bridge that gap.',LIST_TAGS,'How schema theory explains listening comprehension gaps and how a better lead-in can level the playing field.'),
    lesson(158,'Authentic vs graded listening','Authentic recordings expose learners to real connected speech; graded recordings control load. The right choice depends on level and lesson stage.','At A2, a slowed podcast with clear speakers builds confidence. At B2, the same unedited podcast challenges and prepares for the real world.','Review one graded text you use. What authentic alternative exists, and at what level would you switch?',LIST_TAGS,'When to use authentic versus graded listening texts, and how to decide by level and lesson aim.'),
    lesson(159,'How accents affect comprehension','Learners tuned to one accent — often British or American — struggle with Scottish, Irish, Indian, or Australian speakers. Accent exposure is a teaching goal, not a side-effect.','A learner who scores 90% on a BBC listening task may score 40% lower hearing the same information from a Glaswegian speaker.','Find one listening resource with a non-standard English accent and use it next week.',LIST_TAGS,'Why accent variety matters in listening lessons and a practical tip for broadening learner exposure.'),
    lesson(160,'Note-taking while listening','Note-taking is a productive sub-skill, not a shortcut. Teach learners to write key words and numbers, not full sentences — full sentences cost them the next sentence.','\'Company profits rose in Q3\' → notes: <em>profits ↑ Q3</em>. Full-sentence note: \'Company prof—\' and Q3 is gone.','Give learners a two-minute spoken text. Tell them to note only nouns and numbers. Review what they caught.',LIST_TAGS,'How to teach efficient note-taking during listening tasks, with a practical classroom exercise.'),
    lesson(161,'Dictogloss — the collaborative listening task','Dictogloss is a reconstruction task: play a text at natural speed, learners note key words, then rebuild the meaning in groups. Grammar emerges from communicative need.','Play a news paragraph twice. Learners write individually, then compare notes and rebuild the text in pairs. No transcript yet — that comes after.','Write a 60-word dictogloss paragraph on a topic your class has studied this month.',LIST_TAGS,'How dictogloss works and why it integrates listening, grammar, and speaking in one short task.'),
    lesson(162,'The listen-and-repeat trap','Drilling isolated sentences builds pronunciation patterns but not real listening. Learners who only ever repeat a model cannot handle unpredictable connected speech.','A learner drills \'Can I help you?\' perfectly, then cannot parse \'Cannahelp cha?\' from a fast American cashier.','Add one unpredictable spontaneous question to any drilling activity this week. Note what happens.',LIST_TAGS,'Why drilling alone is insufficient for listening development and how to introduce unpredictability.'),
    lesson(163,'Why learners miss words: connected speech','In fast speech, words link, reduce, and disappear. Learners taught vocabulary in isolation cannot recognise those words in the natural stream.','\'Did you eat yet?\' → /dɪdjʊiːtjet/ — two words missing, two merged.','Choose five common questions from your course book. Write the connected-speech form of each. Teach both versions.',LIST_TAGS,'How connected speech causes listening comprehension failures and how to teach learners to cope with it.'),
    lesson(164,'Elision and assimilation','Elision means sounds drop out (<em>next door</em> → /neks dɔː/). Assimilation means a sound changes to match its neighbour (<em>ten minutes</em> → /tem mɪnɪts/). Both are normal spoken English, not lazy speech.','\'Good morning\' → /gʊm mɔːnɪŋ/ — the /d/ assimilates to the following /m/.','Find three examples of assimilation in a course-book dialogue. Mark them for learners before they listen.',LIST_TAGS,'What elision and assimilation are in English phonology, with classroom examples teachers can use today.'),
    lesson(165,'Linking in fast speech','When a word ends in a consonant and the next begins with a vowel, the sounds link. This is the single biggest cause of missed words at A2–B1.','\'Turn it off\' → /tɜːnɪtɒf/ — one continuous sound, not three separate words.','Dictate five linked phrases to your class at natural speed. How many do they hear as one word?',LIST_TAGS,'How consonant-vowel linking in English creates comprehension problems and how to teach it explicitly.'),
    lesson(166,'Weak forms in the stream of speech','Function words — articles, prepositions, auxiliaries — reduce to a schwa or disappear in natural speech. Learners trained on strong forms are unprepared for real listening.','\'I was at the station\' → /aɪ wəz ət ðə steɪʃən/ — three function words weakened.','Mark the weak forms in three sentences from tomorrow’s listening. Pre-teach the reduced versions.',LIST_TAGS,'Why weak forms create listening difficulties and a simple strategy for pre-teaching reduced speech.'),
    lesson(167,'Extensive listening — low-stress input','Extensive listening is high-volume, self-chosen, largely understood content. Comprehensible input applied to listening. Fluency grows from quantity, not from intensive drilling alone.','A learner who watches one subtitled English comedy series per week, without pausing to look words up, builds speed and pattern recognition over time.','Recommend one free listening source at your learners’ level this week. No tasks. Just listen.',LIST_TAGS,'What extensive listening is, why it builds fluency, and how to recommend it to your learners today.'),
    lesson(168,'Staging a listening lesson','Three stages, always in this order: pre-listening (activate schema, remove blockers) → while-listening (task) → post-listening (exploit the text, produce something). Skipping pre is the most common lesson-design error.','Pre: show a hospital photo, elicit vocabulary. While: gist then detail task. Post: role play using the language just heard.','Audit your next listening lesson against this three-stage sequence. Which stage do you usually cut short?',LIST_TAGS,'The three-stage listening lesson sequence and why the pre-listening stage is the most commonly cut.'),
    lesson(169,'Post-listening tasks that develop the text','Post-listening is where language learning deepens. The text becomes a springboard: discuss opinions, analyse the grammar, role-play a follow-up. \'Discuss in pairs\' is not a post-listening task.','After a job interview dialogue, learners analyse the interviewer’s questions, then conduct their own interview using the same structure.','Replace an open \'discuss in pairs\' with a structured post-listening task for your next lesson.',LIST_TAGS,'How to design productive post-listening tasks that turn a listening text into a springboard for production.'),
    lesson(170,'Reading vs listening — different processing demands','Reading allows re-reading; listening does not. But reading requires decoding written symbols; listening already knows the sound. Both skills need explicit teaching.','An oral learner may speak fluently but read slowly — decoding words on the page is a separate skill from understanding spoken language.','Identify one learner who performs very differently on reading versus listening tasks. What does the gap tell you about their needs?',REC_TAGS,'How reading and listening differ as cognitive processes and what that means for skills teaching in ELT.'),
    lesson(171,'Top-down reading — what readers bring','Top-down reading means using title, headings, layout, and prior knowledge to predict and check meaning before decoding every word.','A reader seeing the headline <em>Markets fall on rate fears</em> already expects vocabulary like \'investors\', \'central bank\', \'percent\'.','Before your next reading lesson, ask learners to predict five words the text contains. Tick them as they find each one.',READ_TAGS,'How top-down processing works in reading and a simple prediction task that activates it in class.'),
    lesson(172,'Bottom-up reading — decoding the page','Bottom-up reading processes phoneme to word, word to clause. It is essential for new scripts, low-frequency vocabulary, or technical precision where context cannot compensate.','A nurse reading a drug dosage must decode bottom-up — every milligram matters; \'0.5\' misread as \'5\' cannot be corrected by context.','Choose a short paragraph with three technical terms. Remove context clues. Can learners still decode the meaning accurately?',READ_TAGS,'When bottom-up reading is essential and how to teach decoding skills alongside top-down comprehension strategies.'),
    lesson(173,'Gist reading — skimming and scanning','Skimming = read fast for the general idea. Scanning = search for one specific item. Both require learners to ignore most of the text — that is the skill, not a shortcut.','Skimming: \'What is this article mainly about?\' Scanning: \'Find the date the law was passed.\'','Set a 90-second skimming task before any detailed reading this week. Time it strictly.',READ_TAGS,'The difference between skimming and scanning in reading, with timed classroom tasks for each.'),
    lesson(174,'Reading for detail — intensive skills','Intensive reading demands close, careful attention to a short text. It builds accuracy and language awareness, not reading speed. Use it after gist work.','\'Find three reasons the author gives for the argument\' requires learners to read every sentence, not skim or scan.','Write one detail question per paragraph of a text you use. Map each question to its paragraph before the lesson.',READ_TAGS,'What intensive reading is, when to use it, and how to write paragraph-level detail questions.'),
    lesson(175,'Inferring meaning from context','Guessing unknown words from context is a core reading strategy. Teach learners to use part of speech, surrounding sentence, and topic before reaching for a dictionary.','\'The hidalgo strode into the room, his cloak billowing.\' Hidalgo is a person — male, formal, historical. Enough meaning to continue reading.','Blank out five words from a paragraph. Learners guess from context, then check. Discuss how they guessed each word.',READ_TAGS,'How to teach vocabulary inferencing from context as a reading strategy, with a cloze-based classroom task.'),
    lesson(176,'Jigsaw reading','Jigsaw reading gives different groups different texts, then mixes groups so each learner teaches their part to the others. This creates a genuine communicative purpose for reading.','Three groups read three news articles on the same event. Regrouped, one person from each shares their story. What information differs? What is missing from each source?','Find three short texts on one topic and design a jigsaw reading task for your next class.',READ_TAGS,'How jigsaw reading works and why it creates a genuine reason to both read carefully and speak.'),
    lesson(177,'Grading reading texts','A text is appropriately graded when learners understand roughly 95% of the words — enough challenge without overload. Below that threshold, learners stop reading for meaning.','Nation’s vocabulary research suggests one unknown word per 100 known words for fluency reading; up to five per 100 for vocabulary growth.','Count unknown words in a text you plan to use. Is it within the 95% comprehensible zone?',READ_TAGS,'How to apply Nation’s 95% comprehensibility rule when selecting reading texts for your class.'),
    lesson(178,'Pre-teaching vocabulary — the gating problem','Pre-teaching every unknown word defeats the purpose of reading. Only pre-teach words that would block all understanding — \'gate\' vocabulary that unlocks the whole text.','Pre-teach <em>embargo</em> before a trade-war text. Leave <em>tariff</em> and <em>export</em> — context and cognates carry those.','From your next reading text, identify two truly gating words. Pre-teach only those.',READ_TAGS,'The gating vocabulary principle: which words to pre-teach before a reading task and which to leave.'),
    lesson(179,'Extensive reading — building fluency','Extensive reading means large volumes of self-chosen, largely understood text read for pleasure. It is the most reliable route to reading fluency (Nation’s research). No tasks, no comprehension checks.','A B1 learner reading one graded reader per week for a school year gains measurably in vocabulary size, grammar accuracy, and reading speed.','Start a class reading log. Learners record title, pages read, and one sentence about it each week.',READ_TAGS,'Extensive reading for fluency: what it is, why Nation’s research supports it, and how to start a class log.'),
    lesson(180,'Reading aloud — when it helps and when it does not','Reading aloud focuses attention on decoding — pronunciation, not meaning. Use it for phonics with young learners or dialogue performance; avoid it as a comprehension tool.','Round-robin reading (each learner reads a paragraph aloud) reduces comprehension: the next reader is rehearsing their turn, not listening to the current one.','Replace round-robin reading with silent reading followed by one comprehension question. Compare the quality of answers.',READ_TAGS,'When reading aloud helps in ELT (phonics, dialogue) and when it hinders comprehension (round-robin).'),
    lesson(181,'Month 6 review — receptive skills','Month 6 covered listening (top-down vs bottom-up, staging, connected speech) and reading (skimming, scanning, grading texts, pre-teaching vocabulary). The thread: input must be comprehensible, purposeful, and staged.','Listening: lead-in → gist task → detail task → post-listening production. Reading: predict → skim → scan → intensive → respond.','Audit one recent receptive skills lesson against either model. What stage did you cut? Plan to restore it. Month 7 ahead: productive skills.',REC_TAGS,'A review of Month 6 receptive skills: the key principles for listening and reading lessons in ELT.'),
    # MONTH 7: PRODUCTIVE SKILLS (D182-D212)
    lesson(182,'Speaking vs talking — what classroom tasks do','Learners talk all day. Speaking tasks give them specific language to practise in a communicative context. A task without a communicative goal is a drill, not a speaking activity.','\'Discuss your weekend\' = talking. \'Persuade your partner to visit your hometown, giving three concrete reasons\' = a speaking task with a goal.','Rewrite one discussion prompt from your course book to include a clear communicative goal and a measurable outcome.',SPK_TAGS,'The difference between unstructured talking and a properly designed speaking task with a communicative goal.'),
    lesson(183,'Accuracy vs fluency — the teacher’s choice','Accuracy activities focus on correct form; fluency activities build speed and confidence. Every speaking task sits on a spectrum. Name your aim before you design the task.','Drilling \'I used to + verb\' = accuracy. \'Tell your partner about your childhood for two minutes without stopping\' = fluency.','Label three speaking activities in your course book A (accuracy), F (fluency), or A+F. Were they designed with that distinction in mind?',SPK_TAGS,'How accuracy and fluency differ as speaking aims, and why naming your aim changes how you design the task.'),
    lesson(184,'Drilling — why, when, and how','Drilling fixes the sound and rhythm of new language in muscle memory. Use it after presentation, before freer practice — never as a lesson in itself.','Choral drill → individual drill → back-chain drill for long chunks: <em>haven’t I been waiting for this</em>.','Drill one target structure using all three types: choral, individual, back-chain. Note which learners still need correction at the end.',SPK_TAGS,'How to use choral, individual, and back-chain drilling effectively to fix pronunciation and form.'),
    lesson(185,'Controlled to free practice — bridging the gap','Controlled practice constrains form (fill the gap, substitute one word). Free practice gives full communicative choice. Jumping straight from a drill to a role play leaves the gap too large.','Controlled: complete the dialogue with a modal verb. Semi-controlled: choose which modal fits your situation. Free: negotiate a real decision using modals naturally.','Add a semi-controlled stage to your next grammar lesson, between the drill and the free production task.',SPK_TAGS,'Why semi-controlled practice bridges the gap between drilling and free speaking tasks in the ELT lesson.'),
    lesson(186,'The information gap task','An information gap is the simplest communicative speaking task: student A holds information that B needs, and vice versa. Speaking happens because it must.','Student A has a train timetable with three times missing. Student B has those missing times but different gaps. They ask and answer until both tables are complete.','Design one information gap task using a topic from your current unit. Write what each student knows that the other needs.',SPK_TAGS,'How information gap tasks create genuine communication in the classroom and how to design one in minutes.'),
    lesson(187,'Role play — three reasons it fails','Role play fails when learners do not understand the situation, lack the language for it, or care too much about accuracy to speak at all. Fix the scenario card, not the activity.','\'Be a customer in a shop\' fails at A2. \'You want to return a blue jacket bought yesterday — it has a broken zip\' gives learners something specific to say.','Take a role play that went badly in your class. Rewrite the scenario card to be more concrete and contain the key vocabulary.',SPK_TAGS,'Why role plays fail in ELT and how a better scenario card fixes all three common problems.'),
    lesson(188,'Discussion tasks — the problem of unequal turns','In open discussion, confident speakers dominate and quieter learners produce nothing. Structured turns, written preparation, and talking tokens level the participation.','\'Discuss\' with six learners = two speak, four wait. \'Each person states one point using the prompt card, then pass\' = all six contribute.','Add a turn structure or a talking token rule to your next discussion task.',SPK_TAGS,'How to fix the unequal-turn problem in discussion tasks with structured participation techniques.'),
    lesson(189,'Monitoring — what to do while learners speak','While learners do a speaking task, the teacher’s job is to listen, note language, and not interrupt — unless a learner is completely stuck. Facilitate, do not teach.','Move quietly around the room. Note three strong uses of target language and two errors. Use both in your delayed feedback, not during the task.','Prepare a monitoring grid: one column for strong language, one for errors. Use it in your next speaking lesson.',SPK_TAGS,'What teachers should do while monitoring a speaking task and how a monitoring grid makes feedback better.'),
    lesson(190,'Content feedback vs language feedback','Give content feedback first — validate the communicative act — before correcting language. This tells learners the message matters, not only the form.','After a learner explains a plan: \'Your three steps were clear. I also noticed <em>I am agree</em> — the correct form is <em>I agree</em>.\'','In your next speaking lesson, give one content comment before any language correction for each learner.',SPK_TAGS,'Why content feedback should precede language correction, and a simple model for delivering both.'),
    lesson(191,'Delayed error correction — the board trick','Write anonymised errors on the board during a fluency task. After the task, learners correct them together. Class-built correction; no individual embarrassment.','Board during task: <em>I enjoyed to swim.</em> After task: \'Who can spot the error? What is the correct form and why?\'','During a five-minute speaking task, note four errors on a clipboard. After the task, put them on the board for peer correction.',SPK_TAGS,'How delayed error correction using the board works and why it is less inhibiting than on-the-spot correction.'),
    lesson(192,'Writing as process vs product','Product writing aims at a finished text. Process writing stages the journey: brainstorm → draft → peer review → revise → final. Process builds transferable skills; product builds text-type knowledge.','Product task: \'Write a formal email.\' Process task: plan audience and purpose → draft → swap with a partner → revise → final version.','Take a product writing task and add two stages: peer feedback and a revision pass.',WRT_TAGS,'The difference between product and process writing in ELT, and how to add process stages to existing tasks.'),
    lesson(193,'Process writing — plan, draft, revise, edit','Four stages, four cognitive tasks. Planning builds ideas; drafting releases them; revision improves content and structure; editing fixes surface form. Never mix revision and editing.','At the revision stage, learners ask \'Is the message clear?\' not \'Is the spelling right?\' — that question belongs to editing.','Give learners a colour-coding task: mark each section of their draft with the stage it represents (plan / draft / revision / edit).',WRT_TAGS,'The four stages of process writing and why keeping revision and editing separate produces better texts.'),
    lesson(194,'Genre in writing — text types matter','Each text type has a predictable structure, register, and social purpose. Teaching the genre explicitly gives learners the skeleton before they fill it with language.','A complaint email follows: opening reference → specific problem → impact → requested action → polite close. Once learners see the pattern, the language fills itself.','Choose one writing task you teach. Map the genre structure explicitly with your class before they write a word.',WRT_TAGS,'Why genre knowledge matters in writing instruction and how to teach text structure before language.'),
    lesson(195,'Peer correction in writing','Peer correction builds editing skills, reduces teacher marking load, and creates a real audience for writing. It only works with a structured checklist — not \'check your partner’s work\'.','Checklist: (1) Does the text have an opening, middle, and close? (2) Is the register consistent? (3) Circle two phrases you found effective.','Write a three-item peer feedback checklist tailored to your next writing task.',WRT_TAGS,'How peer correction works in writing classes and why a structured checklist is essential for it to succeed.'),
    lesson(196,'Teacher feedback on writing — less is more','Marking every error overwhelms learners and trains them to hunt for red pen, not to read for meaning. Target feedback to the lesson aim only.','A B1 essay task aimed at argument structure: comment on structure and one language pattern. Leave spelling for the learner to self-correct.','On your next marking batch, limit yourself to two feedback points per script, both tied directly to the lesson aim.',WRT_TAGS,'Why targeted, aim-focused feedback on writing outperforms comprehensive error marking.'),
    lesson(197,'Dictation — a neglected productive task','Dictation integrates listening, spelling, punctuation, and grammar in a single task. It is not a test — it is focused practice. Adjust speed and repetitions to control difficulty.','Read a sentence at natural speed, pause, repeat. Learners write, compare with a partner, then see the original — three types of noticing in one pass.','Use a dictation for the first five minutes of your next class, drawing on target language from the previous lesson.',WRT_TAGS,'How to use dictation as a productive practice task that integrates listening, writing, and grammar.'),
    lesson(198,'Collaborative writing tasks','Writing together removes blank-page panic, promotes discussion about language choices, and produces a shared text learners feel invested in.','Groups of three write one sentence each in rotation, building a story. Or co-author a class guide to their city for an imaginary new student.','Design one collaborative writing task where every learner contributes at least two sentences.',WRT_TAGS,'Why collaborative writing tasks work and how to design one that ensures equal contribution from every learner.'),
    lesson(199,'The learner journal — extensive writing at low stakes','A learner journal is regular, personal, ungraded writing. It builds writing habit, fluency, and vocabulary without product pressure. Teachers respond to the content, not the errors.','\'Write five sentences about your week, your opinion, or a question you have\' — weekly, five minutes, no red pen.','Introduce a journal task this week. Respond to two learners’ content with your own view. Do not correct grammar.',WRT_TAGS,'What a learner journal is, why it builds writing fluency, and how teachers should respond to it.'),
    lesson(200,'Mixed-ability speaking groups — roles that equalise','Mixed-ability speaking groups fail when stronger learners dominate. Role cards that assign specific responsibilities force every learner to contribute regardless of level.','Role cards: Timekeeper (controls who speaks how long), Reporter (shares the group’s conclusion), Devil’s Advocate (must challenge at least one point).','Assign one structured role per learner in your next group speaking task.',MA_TAGS,'How to use role cards to equalise participation in mixed-ability speaking groups.'),
    lesson(201,'Receptive to productive — the skills bridge','Receptive input feeds productive output. Learners cannot speak or write language they have never encountered in listening or reading. Plan a reading-to-speaking or listening-to-writing bridge.','Learners read three opinions on a topic → choose one they agree or disagree with → write a response → share it with the group.','In your next unit, trace one language item from input (listening or reading) to output (speaking or writing). Show learners the journey.',PRO_TAGS,'How to build a bridge from receptive input to productive output so learners use what they have read or heard.'),
    # SPECIALIST: YOUNG LEARNERS (D202-D204)
    lesson(202,'Teaching young learners — what is different','Young learners have shorter attention spans, learn through play and movement, and acquire language holistically. They need variety, physical activity, and clear routines — not condensed adult lessons.','An adult may focus on a grammar explanation for 20 minutes. A seven-year-old needs a task change every 8–10 minutes to stay engaged.','Count the task changes in your next young learner lesson. Aim for at least one every 10 minutes.',YL_TAGS,'How young learner ELT differs from adult teaching: attention, play, movement, and routine.'),
    lesson(203,'Phonics for young learners — the basics','Phonics teaches the relationship between letters and sounds systematically. It is the most evidence-based approach to building reading in young learners of English.','Teaching that <em>sh</em> makes one sound /ʃ/ (ship, shop, she) before learners try to read connected text prevents guessing and builds decoding confidence.','Find one phonics activity targeting a sound your young learners regularly confuse in their written work.',YL_TAGS,'Why phonics is the evidence-based foundation for young learner reading in English and how to start.'),
    lesson(204,'Songs and chants in the young learner classroom','Repetition in songs and chants drills rhythm, pronunciation, and vocabulary with zero tedium. Young learners do not tire of a song they enjoy.','<em>Head, shoulders, knees and toes</em> teaches body parts through kinaesthetic reinforcement. The ABC song makes sequence memorable.','Find one chant that practises a grammar point — not just vocabulary — and use it this week.',YL_TAGS,'Why songs and chants are not just fun but effective pronunciation and vocabulary tools for young learners.'),
    # SPECIALIST: BUSINESS ENGLISH / PROFESSIONAL (D205-D206)
    lesson(205,'Business English — needs analysis first','Professional learners have specific, job-related language needs. A needs analysis interview before teaching identifies what they must actually do in English: meetings, reports, emails, calls.','A financial analyst presenting quarterly data has very different language needs from a receptionist handling enquiries. Same CEFR level; entirely different content.','Write five needs analysis questions you would ask a new professional learner before planning a single lesson.',BE_TAGS,'Why needs analysis must precede course design in Business English and five questions to ask every professional learner.'),
    lesson(206,'Business English — email register','Register in professional writing means matching tone to the relationship and purpose: formal, semi-formal, or informal. Wrong register signals cultural mismatch, not just grammar error.','\'Per my last email…\' reads as passive-aggressive in many professional cultures. \'As I mentioned on Monday…\' achieves the same reference with a neutral tone.','Give learners three versions of the same email at different register levels. They decide which to send and to whom, then justify the choice.',BE_TAGS,'How to teach register awareness in professional email writing, with a three-version comparison task.'),
    # SPECIALIST: MIXED ABILITY (D207-D210)
    lesson(207,'Mixed ability — the reality','A mixed-ability class is not a problem to solve; it is the normal classroom. The goal is not to standardise outcomes but to give every learner an appropriate challenge.','One reading task, three question sets: A (simpler, more contextual clues), B (standard), C (evaluative, open-ended). Same text; different entry points.','Take one task you teach and write a simplified version and an extension. Use all three versions next week.',MA_TAGS,'How to reframe mixed-ability classes as normal and use tiered tasks to provide appropriate challenge for all.'),
    lesson(208,'Differentiation — the open task','An open task has no fixed right answer and can be completed at any level of depth. It differentiates naturally without requiring the teacher to write three separate versions.','\'Write a description of your neighbourhood.\' A1 writes three sentences; B2 writes a structured paragraph with contrast and opinion. Same task; different outcomes.','Find one closed task in your current materials and make it open by removing the fixed answer constraint.',MA_TAGS,'How open tasks differentiate naturally in a mixed-ability class without requiring separate materials.'),
    lesson(209,'Mixed levels together — pairing strategies','Pair stronger learners with weaker ones for production tasks; pair same-level learners for accuracy tasks. The goal determines the grouping, not class convention.','Accuracy drill: pair by level so feedback is appropriate. Discussion task: pair mixed so weaker learners gain richer input and stronger learners consolidate.','Deliberately vary your pairing strategy in your next lesson: same-level for controlled practice, mixed-level for freer production.',MA_TAGS,'When to pair same-level and when to pair mixed-level learners, and how the task aim decides.'),
    lesson(210,'Assessing mixed-ability classes fairly','Standardised tests measure all learners against the same benchmark. In mixed-ability classes, progress-based assessment — measuring individual gain — is more motivating and more honest.','A learner who moves from A1 to A2 in one term has made outstanding progress, even if the class average is B1. Document that gain explicitly.','Write one progress-based feedback comment per learner this week, focused on what each can do now that they could not do one month ago.',MA_TAGS,'Why progress-based assessment is fairer than standardised benchmarks in mixed-ability ELT classes.'),
    # ERROR CORRECTION + REVIEW (D211-D212)
    lesson(211,'Error correction — when and why','Immediate error correction interrupts fluency and can inhibit risk-taking. Delayed correction collects errors during the task and addresses them after. Match the type to the aim.','Accuracy task: correct immediately. Fluency discussion: note errors quietly, correct after. Never interrupt a fluency task with form focus.','At the start of your next lesson, decide: immediate or delayed correction. Commit to it for the whole session.',ERR_TAGS,'When to correct immediately versus delay error correction, based on whether the task aim is accuracy or fluency.'),
    lesson(212,'Month 7 review — productive skills','Month 7 covered speaking (accuracy vs fluency, drilling, monitoring, feedback) and writing (process, genre, peer correction, journals). Core principle: production needs preparation and a communicative purpose.','Speaking: model → controlled → semi-controlled → free task → content feedback → delayed language feedback. Writing: model → genre analysis → draft → peer review → revise.','Map your next speaking and writing lessons to these sequences. Identify the missing stage and plan to add it.',PRO_TAGS,'A review of Month 7 productive skills: the full speaking and writing lesson sequences in ELT.'),
]


def main():
    total = len(LESSONS)
    ok = 0
    failed = 0

    print(f'Publishing {total} lessons to WordPress as drafts...\n')

    for i, post in enumerate(LESSONS, 1):
        code, body = wp_post(post)
        success = 200 <= code < 300
        if success:
            ok += 1
            status = 'OK '
        else:
            failed += 1
            status = 'ERR'
        title_short = post['title'][:70]
        print(f'[{i:3}/{total}] {status} HTTP {code}  {title_short}')
        if not success:
            print(f'            Response: {body[:300]}')
        results_log = {'title': post['title'], 'http': code, 'ok': success}
        time.sleep(0.4)

    print(f'\n{"="*60}')
    print(f'Total: {total}  |  Posted OK: {ok}  |  Failed: {failed}')
    return 0 if failed == 0 else 1


if __name__ == '__main__':
    sys.exit(main())
