TITLE = "Heroes, Networks, and Credit"
SUBTITLE = "History Investigation — 28 September 2026, 08:00 Réunion"
PALETTE = {
    "ink": "#28333c",
    "paper": "#f2e8cf",
    "teal": "#327c78",
    "coral": "#c5604f",
    "gold": "#d3a13d",
    "blue": "#567da0",
    "green": "#70895e",
}

CARDS = [
    {
        "id": "rosa-parks-network",
        "title": "Rosa Parks was prepared",
        "question": "Was one refusal enough?",
        "body": """**Documented fact.** Rosa Parks joined Montgomery’s NAACP. That happened during 1943. She served as secretary. Her work included investigations. She documented racial violence. During August 1955, she attended Highlander. Its workshop taught desegregation organizing. Parks refused relocation later. Police arrested her December 1. The Women’s Political Council mobilized. It announced the first boycott. Local churches supported transport. The Montgomery Improvement Association formed. Lawyers pursued *Browder v. Gayle*. Earlier resisters included Claudette Colvin. **Scholarly interpretation.** Parks’s arrest became catalytic. Her standing aided mobilization. Prepared networks converted defiance. A lone gesture did not. **Benefits.** One person clarified injustice. Her case unified action. **Counterevidence and limits.** Parks acted from conviction. Evidence shows no staged arrest. Earlier cases faced obstacles. Organizers made strategic choices. Public memory simplified coordination. That memory preserves courage. It can erase colleagues. The boycott required thousands. Legal victory used several plaintiffs. History needs both levels.""",
        "summary": "Prepared networks converted defiance.",
        "sources": [
            ["Places of Rosa Parks", "https://www.nps.gov/articles/000/places-of-rosa-parks.htm"],
            ["The Bus Boycott", "https://www.loc.gov/exhibitions/rosa-parks-in-her-own-words/about-this-exhibition/the-bus-boycott/"],
            ["Highlander Folk School", "https://www.loc.gov/exhibitions/rosa-parks-in-her-own-words/about-this-exhibition/the-bus-boycott/highlander-folk-school/"],
            ["Montgomery Bus Boycott", "https://www.nps.gov/articles/montgomery-bus-boycott.htm"],
        ],
        "beats": ["Parks builds organizing experience.", "A bus demand arrives.", "Arrest activates local networks.", "Boycott systems replace buses.", "Plaintiffs change the law."],
        "setting": "Montgomery bus and network",
        "objects": [
            {"kind":"portrait","label":"Rosa Parks","fact":"Parks had organized since 1943.","track":[[90,218],[125,210],[160,203],[195,196],[225,190],[250,184]],"from":0},
            {"kind":"bus","label":"segregated bus","fact":"Police arrested Parks December 1.","track":[[565,235],[515,230],[465,224],[415,218],[365,212],[325,206]],"from":1},
            {"kind":"leaflet","label":"boycott notice","fact":"The Women’s Political Council mobilized.","track":[[565,105],[520,115],[475,128],[430,142],[385,158],[350,175]],"from":2},
            {"kind":"group","label":"walking riders","fact":"Thousands sustained the boycott.","track":[[575,235],[535,225],[495,215],[455,205],[415,195],[380,188]],"from":3},
            {"kind":"car","label":"carpool network","fact":"Carpools replaced bus journeys.","track":[[85,265],[155,255],[230,245],[305,235],[380,225],[455,215]],"from":3},
            {"kind":"gavel","label":"Browder ruling","fact":"Several plaintiffs changed the law.","track":[[585,130],[585,130],[585,130],[540,140],[495,155],[450,175]],"from":4},
        ],
    },
    {
        "id": "einstein-szilard-letter",
        "title": "Einstein’s signature carried access",
        "question": "Did one letter build?",
        "body": """**Documented fact.** Nuclear fission emerged during 1938. Leo Szilard feared weaponization. He involved Eugene Wigner. Edward Teller also helped. Szilard drafted a warning. Albert Einstein signed it. The letter reached Roosevelt. Delivery occurred October 11, 1939. Roosevelt formed an advisory committee. Its first meeting followed. That happened October 21. Early support stayed limited. Wartime research then expanded. British findings added urgency. American entry changed scale. The Army created Manhattan District. **Scholarly interpretation.** Einstein supplied public authority. Szilard supplied initiative. The signature opened presidential attention. It did not design bombs. **Benefits.** Early warning funded research. Fear addressed genuine uncertainty. **Counterevidence and limits.** German capability was overestimated. The letter was catalytic. It was not sufficient. Later science mattered more. Military organization mattered too. Industrial production became decisive. Calling Einstein the creator misstates causation. Removing the letter changes timing. It cannot prove failure.""",
        "summary": "A signature opened attention.",
        "sources": [
            ["Einstein–Szilard Letter", "https://ahf.nuclearmuseum.org/ahf/key-documents/einstein-szilard-letter/"],
            ["Manhattan Project History", "https://www.nps.gov/mapr/learn/manhattan-project.htm"],
            ["Einstein’s Letter, 1939", "https://www.osti.gov/opennet/manhattan-project-history/Events/1939-1942/einstein_letter.htm"],
            ["Early Government Support", "https://www.osti.gov/opennet/manhattan-project-history/Events/1939-1942/1939-1942.htm"],
        ],
        "beats": ["Szilard frames the warning.", "Einstein lends public authority.", "Roosevelt receives the letter.", "A committee funds research.", "War scales the system."],
        "setting": "Letter, presidency, and laboratories",
        "objects": [
            {"kind":"scientist","label":"Leo Szilard","fact":"Szilard initiated the warning.","track":[[90,225],[120,218],[150,210],[180,202],[210,195],[235,188]],"from":0},
            {"kind":"envelope","label":"signed letter","fact":"Einstein’s name carried authority.","track":[[150,170],[225,165],[300,160],[375,155],[450,150],[515,145]],"from":1},
            {"kind":"portrait","label":"Einstein","fact":"Einstein signed the warning.","track":[[100,105],[145,115],[190,128],[235,142],[280,158],[320,175]],"from":1},
            {"kind":"table","label":"uranium committee","fact":"Roosevelt formed an advisory committee.","track":[[565,230],[525,220],[485,210],[445,200],[405,190],[370,180]],"from":2},
            {"kind":"atom","label":"chain reaction","fact":"Scientific results changed feasibility.","track":[[575,105],[530,115],[485,130],[440,145],[395,160],[355,178]],"from":3},
            {"kind":"factory","label":"wartime system","fact":"Military and industry scaled production.","track":[[585,135],[585,135],[585,135],[540,145],[495,160],[450,180]],"from":4},
        ],
    },
    {
        "id": "ada-lovelace-collaboration",
        "title": "Lovelace published a program",
        "question": "Who counts as first?",
        "body": """**Documented fact.** Charles Babbage designed engines. Ada Lovelace studied his work. She translated Menabrea’s account. Her notes tripled its length. Publication came during 1843. Note G described Bernoulli numbers. It gave sequenced operations. The Analytical Engine remained unfinished. Therefore, this program never ran. Babbage’s notebooks contained algorithms. Their collaboration shaped the publication. Lovelace also imagined wider uses. Numbers could represent symbols. They could represent music. **Scholarly interpretation.** Note G became foundational. It is often called first. That label depends upon definitions. Published algorithm differs from execution. Programming also predates electronic computers. **Benefits.** The label restores visibility. It expands computing history. **Counterevidence and limits.** Lovelace did not build hardware. Babbage supplied machine architecture. He had sketched procedures earlier. Their correspondence shows collaboration. Individual credit remains debatable. Her general-purpose insight stands. Calling her merely translator fails. Calling her sole originator fails too.""",
        "summary": "Publication emerged through collaboration.",
        "sources": [
            ["Women in Computing", "https://www.sciencemuseum.org.uk/objects-and-stories/women-computing"],
            ["Ada Lovelace: Visionary", "https://blog.sciencemuseum.org.uk/ada-lovelace-visionary-of-the-computer-age/"],
            ["Babbage’s Analytical Engine", "https://collection.sciencemuseumgroup.org.uk/objects/co62245/babbages-analytical-engine-1834-1871-trial-model"],
        ],
        "beats": ["Babbage designs an engine.", "Lovelace translates its account.", "Correspondence reshapes the notes.", "Note G sequences operations.", "An unfinished machine persists."],
        "setting": "Victorian engine workshop",
        "objects": [
            {"kind":"engine","label":"Analytical Engine","fact":"Babbage designed programmable machinery.","track":[[95,225],[125,220],[155,215],[185,210],[215,205],[240,200]],"from":0},
            {"kind":"portrait","label":"Ada Lovelace","fact":"Lovelace expanded Menabrea’s account.","track":[[560,225],[525,220],[490,215],[455,210],[420,205],[390,200]],"from":1},
            {"kind":"envelope","label":"correspondence","fact":"Letters show active collaboration.","track":[[520,110],[470,120],[420,132],[370,145],[320,160],[280,178]],"from":2},
            {"kind":"punchcard","label":"Note G","fact":"Note G sequenced Bernoulli operations.","track":[[95,120],[150,130],[205,142],[260,155],[315,170],[360,185]],"from":3},
            {"kind":"gear","label":"unbuilt machine","fact":"The full engine never operated.","track":[[575,115],[530,125],[485,138],[440,152],[395,168],[355,184]],"from":4},
            {"kind":"document","label":"1843 publication","fact":"Publication made the algorithm visible.","track":[[585,140],[585,140],[585,140],[540,150],[495,165],[450,182]],"from":4},
        ],
    },
    {
        "id": "lamarr-antheil-patent",
        "title": "Lamarr shared the patent",
        "question": "Did she invent Wi-Fi?",
        "body": """**Documented fact.** Hedy Lamarr knew weapons systems. George Antheil composed experimental music. Together, they designed communication. Their transmitter changed frequencies. Its receiver changed synchronously. Jamming therefore became harder. They sought torpedo guidance. A patent arrived during 1942. It named both inventors. The Navy did not deploy it. Neither inventor received royalties. Later systems used spread spectrum. Modern wireless systems use related principles. They also use different methods. Many later engineers contributed. **Scholarly interpretation.** Lamarr’s fame obscured invention. Later retellings reversed neglect. Some now overextend lineage. The patent remains a predecessor. It did not directly create Wi-Fi. **Benefits.** Recognition corrected exclusion. The story broadens invention culture. It challenges narrow inventor stereotypes. **Counterevidence and limits.** Frequency hopping had antecedents. Implementation posed mechanical problems. Patent influence remains disputed. Similarity does not prove direct descent. Antheil’s role also matters. Lamarr deserves inventor credit. Sole-founder language remains unsupported.""",
        "summary": "Two inventors patented synchronization.",
        "sources": [
            ["U.S. Patent 2,292,387", "https://patents.google.com/patent/US2292387A/en"],
            ["Lamarr–Antheil Invention Papers", "https://www.si.edu/object/archives/sova-nmah-ac-1590"],
            ["Hedy Lamarr", "https://www.invent.org/inductees/hedy-lamarr"],
            ["Lamarr’s WWII Invention", "https://www.nationalww2museum.org/war/articles/hedy-lamarrs-wwii-invention-helped-shape-modern-tech"],
        ],
        "beats": ["Lamarr studies torpedo control.", "Antheil maps synchronized timing.", "Radios hop together.", "Jamming loses its target.", "Later systems adapt principles."],
        "setting": "Studio, radio, and torpedo",
        "objects": [
            {"kind":"portrait","label":"Hedy Lamarr","fact":"Lamarr co-designed the system.","track":[[90,225],[125,218],[160,210],[195,202],[225,195],[250,188]],"from":0},
            {"kind":"punchcard","label":"Antheil timing","fact":"Antheil contributed synchronized timing.","track":[[565,225],[525,218],[485,210],[445,202],[405,195],[370,188]],"from":1},
            {"kind":"radio","label":"transmitter","fact":"The transmitter changed frequencies.","track":[[110,120],[165,130],[220,142],[275,155],[330,170],[370,185]],"from":2},
            {"kind":"radio","label":"receiver","fact":"The receiver hopped synchronously.","track":[[550,120],[500,130],[450,142],[400,155],[350,170],[315,185]],"from":2},
            {"kind":"torpedo","label":"guided torpedo","fact":"The design targeted torpedo guidance.","track":[[85,265],[165,255],[245,245],[325,235],[405,225],[485,215]],"from":3},
            {"kind":"patent","label":"1942 patent","fact":"Both inventors held the patent.","track":[[585,135],[585,135],[585,135],[540,145],[495,160],[450,180]],"from":4},
        ],
    },
    {
        "id": "franklin-photo-51",
        "title": "Photo 51 joined evidence",
        "question": "Did one image solve DNA?",
        "body": """**Documented fact.** Rosalind Franklin studied DNA. Raymond Gosling was her student. Together, they made Photo 51. Exposure lasted sixty-two hours. The image showed B-form diffraction. Its cross suggested a helix. Maurice Wilkins held a copy. He showed James Watson. Franklin did not know. Watson and Francis Crick modeled DNA. Other data also informed them. Franklin separately approached the structure. Her paper appeared simultaneously. Gosling shared its authorship. **Scholarly interpretation.** Franklin’s data proved crucial. Her role lacked due recognition. Recent scholarship rejects victim caricatures. It presents an equal contributor. **Benefits.** Corrected history restores credit. Collaboration becomes visible. Shared work gains names. **Counterevidence and limits.** Photo 51 was not everything. Model building added base pairing. Wilkins produced related diffraction. Access practices were ambiguous. Franklin’s consent was absent. “Stolen secret” can oversimplify. “Minor assistant” is false. The discovery joined images, chemistry, models, and several researchers.""",
        "summary": "Images and models converged.",
        "sources": [
            ["The Story Behind Photograph 51", "https://www.kcl.ac.uk/the-story-behind-photograph-51"],
            ["Franklin and Gosling, 1953", "https://www.nature.com/articles/171740a0"],
            ["Watson and Crick, 1953", "https://www.nature.com/articles/171737a0"],
            ["Franklin’s Contribution Revisited", "https://www.nature.com/articles/d41586-023-01313-5"],
        ],
        "beats": ["Franklin prepares DNA fibres.", "Gosling records diffraction.", "Wilkins shows the image.", "Models combine several clues.", "Three papers appear together."],
        "setting": "King’s and Cambridge laboratories",
        "objects": [
            {"kind":"scientist","label":"Franklin","fact":"Franklin directed X-ray analysis.","track":[[90,225],[120,218],[150,210],[180,202],[210,195],[235,188]],"from":0},
            {"kind":"xray","label":"Photo 51","fact":"Gosling and Franklin made the image.","track":[[155,120],[210,130],[265,142],[320,155],[375,170],[415,185]],"from":1},
            {"kind":"portrait","label":"Raymond Gosling","fact":"Gosling shared authorship.","track":[[565,230],[525,222],[485,214],[445,206],[405,198],[370,190]],"from":1},
            {"kind":"envelope","label":"shared data","fact":"Watson saw it without Franklin’s knowledge.","track":[[550,110],[500,120],[450,132],[400,145],[350,160],[310,178]],"from":2},
            {"kind":"model","label":"DNA model","fact":"Model building added base pairing.","track":[[575,115],[530,125],[485,138],[440,152],[395,168],[355,184]],"from":3},
            {"kind":"document","label":"three papers","fact":"Nature published three papers together.","track":[[585,140],[585,140],[585,140],[540,150],[495,165],[450,182]],"from":4},
        ],
    },
    {
        "id": "primitive-echo-leadership",
        "title": "Primitive Echo: focal leaders",
        "question": "Why credit one person?",
        "body": """**Documented evidence.** Small groups face coordination costs. Leadership can reduce them. Field studies examined two societies. Researchers studied Tsimane communities. They also studied Nyangatom communities. Leaders held useful capital. Knowledge could lower costs. Social ties also helped. Leadership often stayed situational. Different tasks produced leaders. Larger problems favored institutions. Other studies found legitimacy matters. Leaders can also damage cooperation. **Evolutionary interpretation.** Human groups needed coordination. A focal person simplified action. Followers could track one signal. Leadership may therefore feel natural. This remains a hypothesis. Modern credit is different. **Current echo.** Projects become founder stories. Movements acquire one face. Teams credit visible coordinators. **Benefits.** Focal leaders speed decisions. They make responsibility legible. **Harms.** Credit can become distorted. Contributors then disappear. Leaders may claim outcomes. **Counterevidence and limits.** Field societies differ. Leadership was often distributed. Evidence does not prove hero worship. Coordination explains attention. It cannot justify monopoly credit.""",
        "summary": "Coordination can distort credit.",
        "sources": [
            ["Leadership Solves Collective Action", "https://pmc.ncbi.nlm.nih.gov/articles/PMC4633846/"],
            ["Leadership in an Egalitarian Society", "https://pmc.ncbi.nlm.nih.gov/articles/PMC4258461/"],
            ["Group Size and Hierarchy", "https://pmc.ncbi.nlm.nih.gov/articles/PMC7341912/"],
        ],
        "beats": ["A group faces coordination.", "One member becomes focal.", "Signals align group action.", "Success attracts visible credit.", "Records restore distributed work."],
        "setting": "Shared task and focal leader",
        "objects": [
            {"kind":"group","label":"working group","fact":"Groups face coordination costs.","track":[[135,225],[170,218],[205,210],[235,202],[260,195],[280,188]],"from":0},
            {"kind":"leader","label":"focal leader","fact":"Leaders can align action.","track":[[520,225],[495,218],[470,210],[445,202],[420,195],[400,188]],"from":1},
            {"kind":"signal","label":"shared signal","fact":"One signal can lower coordination costs.","track":[[320,110],[320,122],[320,136],[320,150],[320,165],[320,180]],"from":2},
            {"kind":"crate","label":"collective result","fact":"Many contributors produce outcomes.","track":[[85,265],[155,255],[230,245],[305,235],[380,225],[455,215]],"from":3},
            {"kind":"spotlight","label":"visible credit","fact":"Visibility can concentrate credit.","track":[[570,110],[525,120],[480,134],[435,150],[390,166],[350,182]],"from":3},
            {"kind":"document","label":"restored record","fact":"Records can restore distributed work.","track":[[585,140],[585,140],[585,140],[540,150],[495,165],[450,182]],"from":4},
        ],
    },
]
