TITLE = "Borders, Bombs, and Bargains"
SUBTITLE = "History Investigation — 28 September 2026, 06:00 Réunion"
PALETTE = {
    "ink": "#24343a",
    "paper": "#f4e7c9",
    "teal": "#287c78",
    "coral": "#c85e4d",
    "gold": "#d8a53b",
    "blue": "#547fa5",
    "green": "#71895b",
}

CARDS = [
    {
        "id": "iran-1953-coup",
        "title": "Oil and fear converged",
        "question": "What drove Iran’s coup?",
        "body": """**Documented fact.** Iran nationalized oil during 1951. Britain opposed the takeover. Negotiations repeatedly failed. Economic pressure then deepened. American policy soon shifted. CIA planning began. British intelligence also participated. Operation TPAJAX targeted Mosaddeq. Propaganda shaped public perceptions. Paid networks mobilized supporters. Military contacts backed removal. The Shah signed decrees. Mosaddeq fell during August. Zahedi received American funds. A consortium later resumed exports. **Benefits claimed.** Officials cited Soviet risks. They sought political stability. Oil production could restart. **Scholarly interpretation.** Oil and anticommunism intertwined. Iranian actors remained decisive. Clerics, officers, and monarchists acted. Crowds also acted. **Counterevidence and limits.** Tudeh influence was real. Yet immediate takeover seemed unlikely. Mosaddeq also weakened parliament. His referendum drew criticism. Domestic conflict preceded intervention. CIA support never acted alone. Declassified records prove involvement. They show planned pressure. They do not prove omnipotence. Later revolutionary anger had sources. The coup shaped that anger. It cannot explain everything.""",
        "summary": "Oil conflict met Cold-War fear.",
        "sources": [
            ["FRUS: Preliminary TPAJAX Plan", "https://history.state.gov/historicaldocuments/frus1951-54IranEd2/d216"],
            ["FRUS: CIA Action Summary", "https://history.state.gov/historicaldocuments/frus1951-54Iran/d363"],
            ["Communism, Cold War, and the 1953 Coup", "https://www.cambridge.org/core/journals/international-journal-of-middle-east-studies/article/communism-cold-war-and-the-1953-coup/C74E89EF37D4CA387A063217D05007F9"],
            ["CIA Capabilities Against Tudeh", "https://history.state.gov/historicaldocuments/frus1951-54Iran/d170"],
        ],
        "beats": ["Iran nationalizes oil.", "Foreign pressure tightens.", "Networks mobilize the coup.", "Mosaddeq loses office.", "Motives remain layered."],
        "setting": "Tehran street and refinery",
        "objects": [
            {"kind":"refinery","label":"nationalized oil","fact":"Iran nationalized oil during 1951.","track":[[80,220],[80,220],[80,220],[80,220],[80,220],[80,220]],"from":0},
            {"kind":"barrel","label":"export blockade","fact":"Economic pressure followed nationalization.","track":[[180,205],[240,198],[300,190],[340,185],[340,185],[340,185]],"from":1},
            {"kind":"file","label":"TPAJAX plan","fact":"American and British agencies planned removal.","track":[[570,105],[520,115],[465,128],[410,145],[360,160],[360,160]],"from":1},
            {"kind":"group","label":"Iranian networks","fact":"Domestic actors remained decisive.","track":[[570,230],[520,222],[470,214],[420,206],[370,198],[370,198]],"from":2},
            {"kind":"portrait","label":"Mosaddeq","fact":"Mosaddeq fell during August 1953.","track":[[320,205],[320,205],[320,205],[330,215],[250,235],[175,250]],"from":0},
            {"kind":"balance","label":"oil and fear","fact":"Scholars weigh oil and anticommunism.","track":[[300,92],[300,92],[300,92],[355,100],[410,112],[455,125]],"from":4},
        ],
    },
    {
        "id": "radcliffe-partition-line",
        "title": "A deadline hardened borders",
        "question": "How was Partition mapped?",
        "body": """**Documented fact.** Britain accelerated imperial withdrawal. Parliament created two dominions. Punjab and Bengal split. Boundary commissions received mandates. Cyril Radcliffe chaired both. He arrived during July. Independence came during August. He lacked local experience. Commissioners deadlocked repeatedly. Radcliffe made final awards. Maps used imperfect census data. Communications also influenced decisions. Awards appeared after independence. Millions then crossed borders. Violence preceded final publication. Violence also followed it. **Benefits claimed.** Leaders sought rapid transfer. Partition promised political settlement. Separate governments avoided deadlock. **Scholarly interpretation.** Speed magnified administrative failure. Delayed disclosure deepened confusion. Religious majorities guided lines. Yet mixed settlements resisted division. **Counterevidence and limits.** Radcliffe did not invent conflict. Communal violence had begun. Congress accepted partition. The Muslim League demanded Pakistan. Sikh leaders contested boundaries. Provincial politics also mattered. Exact casualty totals vary. Migration estimates also vary. Borders alone did not kill. Militias and state collapse mattered. The archival award survives. No single map explains Partition.""",
        "summary": "A rushed award met violence.",
        "sources": [
            ["UK National Archives: Partition of British India", "https://www.nationalarchives.gov.uk/education/teaching-resources/partition-of-british-india/"],
            ["British Library: Boundary Commission Reports", "https://searcharchives.bl.uk/catalog/040-000142912"],
            ["Indian Independence Act 1947", "https://www.legislation.gov.uk/ukpga/1947/30/pdfs/ukpga_19470030_en.pdf"],
            ["UK Parliament: Indian Independence Act", "https://www.parliament.uk/about/living-heritage/evolutionofparliament/legislativescrutiny/parliament-and-empire/collections1/collections2/1947-indian-independence-act/"],
        ],
        "beats": ["Withdrawal accelerates.", "Commissions inherit deadlock.", "A line divides communities.", "Families cross both ways.", "No line explains everything."],
        "setting": "Punjab and Bengal map-room",
        "objects": [
            {"kind":"map","label":"Punjab and Bengal","fact":"Punjab and Bengal were divided.","track":[[120,205],[120,205],[120,205],[120,205],[120,205],[120,205]],"from":0},
            {"kind":"clock","label":"forty days","fact":"The deadline compressed decisions.","track":[[545,105],[510,112],[470,122],[430,135],[400,145],[400,145]],"from":0},
            {"kind":"document","label":"boundary award","fact":"Deadlock left Radcliffe deciding.","track":[[570,215],[520,208],[465,200],[410,192],[355,184],[355,184]],"from":1},
            {"kind":"gate","label":"new border","fact":"The awards appeared after independence.","track":[[320,250],[320,225],[320,200],[320,175],[320,150],[320,150]],"from":2},
            {"kind":"family","label":"eastbound families","fact":"Millions crossed new borders.","track":[[520,245],[470,235],[420,225],[370,215],[310,205],[255,198]],"from":3},
            {"kind":"family","label":"westbound families","fact":"Movement crossed both directions.","track":[[115,245],[165,235],[215,225],[265,215],[325,205],[385,198]],"from":3},
        ],
    },
    {
        "id": "castle-bravo-fallout",
        "title": "Fallout crossed assumptions",
        "question": "Who bore testing risks?",
        "body": """**Documented fact.** America tested Marshall Islands. Residents left Bikini beforehand. Castle Bravo detonated during 1954. Its yield reached fifteen megatons. Planners expected far less. Fallout crossed exclusion assumptions. Rongelap received heavy contamination. Evacuation came after exposure. Utirik residents also evacuated. Lucky Dragon fishermen suffered exposure. Medical monitoring later followed. Rongelap residents returned during 1957. Persistent contamination remained. They left again later. **Benefits claimed.** Officials sought deterrent knowledge. Testing advanced weapon designs. Monitoring offered continuing care. **Scholarly interpretation.** Technical uncertainty met colonial power. Islanders bore imposed risks. Secrecy worsened public distrust. Fallout mobilized testing opposition. **Counterevidence and limits.** Records dispute deliberate exposure claims. An advisory committee found none. Research nevertheless followed exposure. Consent practices were weak. Weather and yield errors differed. Their relative importance remains contested. Health studies faced small samples. Later cancers had multiple causes. The huge fallout stands. Delayed evacuation also stands. Total long-term harm remains debated.""",
        "summary": "Misjudged yield spread fallout.",
        "sources": [
            ["National Security Archive: Castle Bravo at 70", "https://nsarchive.gwu.edu/briefing-book/nuclear-vault/2024-02-29/castle-bravo-70-worst-nuclear-test-us-history"],
            ["National Park Service: Limited Test Ban Treaty", "https://www.nps.gov/articles/000/b-reactor-history-room-limited-test-ban-treaty.htm"],
            ["Advisory Committee: The Marshallese", "https://ehss.energy.gov/ohre/roadmap/achre/chap12_3.html"],
            ["DOE Marshall Islands Program", "https://www.energy.gov/ehss/marshall-islands-program"],
        ],
        "beats": ["A test exceeds forecasts.", "Fallout reaches homes.", "Evacuation follows exposure.", "Monitoring mixes care and study.", "Records bound the claim."],
        "setting": "Bikini and Rongelap atolls",
        "objects": [
            {"kind":"atoll","label":"Bikini","fact":"Testing occurred at Bikini Atoll.","track":[[120,225],[120,225],[120,225],[120,225],[120,225],[120,225]],"from":0},
            {"kind":"bomb","label":"Castle Bravo","fact":"The yield reached fifteen megatons.","track":[[120,95],[155,115],[190,145],[220,180],[220,180],[220,180]],"from":0},
            {"kind":"fallout","label":"fallout cloud","fact":"Fallout reached inhabited atolls.","track":[[210,120],[285,125],[360,132],[435,140],[500,150],[545,160]],"from":1},
            {"kind":"family","label":"Rongelap residents","fact":"Evacuation followed exposure.","track":[[535,225],[535,225],[500,220],[455,215],[395,205],[340,195]],"from":1},
            {"kind":"ship","label":"evacuation","fact":"Residents were evacuated afterward.","track":[[590,255],[540,245],[490,235],[430,225],[365,215],[300,205]],"from":2},
            {"kind":"sample","label":"medical monitoring","fact":"Care and research became entangled.","track":[[575,95],[575,95],[575,95],[520,110],[455,130],[400,150]],"from":3},
        ],
    },
    {
        "id": "east-timor-1975",
        "title": "Allies tolerated invasion",
        "question": "What enabled occupation?",
        "body": """**Documented fact.** Portugal began decolonization. Timorese parties then clashed. Indonesia prepared covert operations. Suharto met President Ford. Kissinger joined that meeting. The meeting preceded invasion. Suharto described likely action. American leaders urged speed. They raised arms-law concerns. Indonesia invaded next day. American weapons supported operations. Aid resumed despite concerns. Occupation lasted until 1999. A Timorese commission documented abuses. **Benefits claimed.** Indonesia cited regional stability. Leaders feared communist influence. Integration promised administrative unity. **Scholarly interpretation.** Cold-War priorities muted opposition. Weapons and diplomacy enabled occupation. Timorese agency still persisted. **Counterevidence and limits.** The invasion was Indonesian. Washington did not command troops. Internal violence preceded invasion. Portugal left weak institutions. Australia also favored integration. Casualty estimates use models. Records remain incomplete. “Green light” describes tolerance. It was not formal authorization. Declassified minutes prove foreknowledge. They prove accommodating language. They cannot recover private intentions. International support later reversed. That reversal enabled intervention. Responsibility therefore had layers.""",
        "summary": "Support lowered invasion costs.",
        "sources": [
            ["National Security Archive: East Timor Revisited", "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB62/press.html"],
            ["FRUS: Indonesia and East Timor", "https://history.state.gov/historicaldocuments/frus1969-76ve12/ch4?start=31"],
            ["Timor-Leste Truth Commission Report", "https://www.etan.org/cavr.htm"],
            ["CAVR Responsibility Findings", "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB176/index.htm"],
        ],
        "beats": ["Decolonization opens conflict.", "Leaders discuss invasion.", "Troops cross next day.", "Foreign weapons sustain operations.", "Responsibility remains layered."],
        "setting": "Jakarta meeting and Timor coast",
        "objects": [
            {"kind":"island","label":"East Timor","fact":"Portugal began decolonization.","track":[[510,225],[510,225],[510,225],[510,225],[510,225],[510,225]],"from":0},
            {"kind":"table","label":"Jakarta meeting","fact":"Suharto described likely action.","track":[[120,205],[170,200],[220,195],[270,190],[270,190],[270,190]],"from":1},
            {"kind":"document","label":"meeting record","fact":"American leaders used accommodating language.","track":[[115,105],[185,112],[255,125],[325,140],[380,155],[380,155]],"from":1},
            {"kind":"ship","label":"invasion force","fact":"Indonesia invaded the next day.","track":[[90,250],[175,240],[260,230],[345,220],[430,210],[500,205]],"from":2},
            {"kind":"crate","label":"American weapons","fact":"American weapons supported operations.","track":[[575,110],[530,122],[480,138],[430,155],[380,172],[340,185]],"from":3},
            {"kind":"magnifier","label":"truth commission","fact":"Later inquiry documented responsibility.","track":[[575,90],[575,90],[575,90],[575,90],[505,105],[440,125]],"from":4},
        ],
    },
    {
        "id": "smallpox-eradication-system",
        "title": "Search built vaccine rings",
        "question": "What eradicated smallpox?",
        "body": """**Documented fact.** WHO targeted global eradication. Early programs stressed vaccination. Coverage stayed uneven. Supplies also remained limited. The 1967 programme intensified work. Surveillance found active cases. Teams traced patient contacts. Those contacts received vaccines. Nearby contacts formed rings. Cases were isolated. Local workers conducted searches. Freeze-dried vaccine improved delivery. Bifurcated needles simplified dosing. Soviet and American teams cooperated. Endemic cases ended during 1977. WHO certified eradication during 1980. **Benefits claimed.** Mass vaccination built immunity. Ring vaccination conserved supplies. Surveillance targeted transmission chains. **Scholarly interpretation.** Systems defeated smallpox. No lone inventor succeeded. Local reporting mattered. International logistics also mattered. **Counterevidence and limits.** Ring methods were older. Foege helped operationalize them. Different regions used mixtures. Mass vaccination remained important. Smallpox had useful biology. Symptoms were recognizable. Humans were its reservoir. Transmission was relatively slow. Therefore, this success transfers imperfectly. Other diseases need alternatives. Eradication also required governance. Vaccines alone were insufficient. Surveillance alone was insufficient. Their combination proved decisive.""",
        "summary": "Surveillance directed scarce vaccines.",
        "sources": [
            ["WHO: History of Smallpox Vaccination", "https://www.who.int/news-room/spotlight/history-of-vaccination/history-of-smallpox-vaccination"],
            ["CDC: Etymologia—Ring Vaccination", "https://wwwnc.cdc.gov/eid/article/30/2/22-1909_article"],
            ["Mass Vaccination and Surveillance-Containment", "https://pmc.ncbi.nlm.nih.gov/articles/PMC7120753/"],
            ["WHO: Smallpox", "https://www.who.int/health-topics/smallpox"],
        ],
        "beats": ["Search teams find cases.", "Contacts form a ring.", "Vaccines target that ring.", "Transmission chains break.", "Systems beat one invention."],
        "setting": "Village search and clinic",
        "objects": [
            {"kind":"patient","label":"reported case","fact":"Surveillance found active cases.","track":[[320,220],[320,220],[320,220],[320,220],[320,220],[320,220]],"from":0},
            {"kind":"runner","label":"search worker","fact":"Local workers searched settlements.","track":[[80,240],[145,230],[210,220],[265,212],[300,208],[300,208]],"from":0},
            {"kind":"ring","label":"contact ring","fact":"Contacts and contacts-of-contacts formed rings.","track":[[320,205],[320,205],[320,205],[320,205],[320,205],[320,205]],"from":1},
            {"kind":"vials","label":"freeze-dried vaccine","fact":"Heat-stable vaccine improved delivery.","track":[[575,110],[525,122],[475,138],[425,155],[375,175],[345,195]],"from":2},
            {"kind":"group","label":"vaccinated contacts","fact":"Targeted vaccination blocked spread.","track":[[560,235],[510,228],[460,220],[410,212],[365,205],[340,200]],"from":2},
            {"kind":"brokenchain","label":"transmission stopped","fact":"Surveillance and vaccination worked together.","track":[[320,95],[320,95],[320,95],[365,105],[415,118],[465,132]],"from":3},
        ],
    },
    {
        "id": "primitive-echo-punishment",
        "title": "Primitive Echo: punishment",
        "question": "Why punish free-riders?",
        "body": """**Documented evidence.** Public-goods experiments test cooperation. People receive shared stakes. Some participants contribute less. Others can punish them. Punishment often costs punishers. Cross-cultural results show variation. Low contributors often face sanctions. High contributors sometimes face them. Elected monitors gain compliance. Random monitors gain less. Field experiments confirm context. **Evolutionary interpretation.** Sanctions can deter free-riding. They may protect shared goods. Reputation may reward enforcers. Cultural learning shapes norms. Institutions can centralize enforcement. **Current echo.** Online groups shame defectors. Workplaces police effort. Nations punish tax evasion. Communities also punish dissent. **Benefits.** Sanctions can stabilize cooperation. Legitimacy reduces needed coercion. **Harms.** Punishment can become antisocial. Envy can target contributors. Group power can silence minorities. **Counterevidence and limits.** Games simplify real societies. Samples differ across studies. Laboratory costs stay small. Culture explains much variation. Genes remain unproven here. Punishment is not automatically adaptive. It works within institutions. Without legitimacy, retaliation grows.""",
        "summary": "Sanctions support or damage cooperation.",
        "sources": [
            ["Costly Punishment Across Human Societies", "https://pubmed.ncbi.nlm.nih.gov/16794075/"],
            ["Antisocial Punishment Across Societies", "https://pubmed.ncbi.nlm.nih.gov/18323447/"],
            ["Centralized Sanctioning and Legitimate Authority", "https://pmc.ncbi.nlm.nih.gov/articles/PMC3131358/"],
            ["Markets, Religion, Community Size, and Fairness", "https://pubmed.ncbi.nlm.nih.gov/20299588/"],
        ],
        "beats": ["Contributors fill the pot.", "One member withholds.", "Peers spend to punish.", "Legitimacy changes compliance.", "Sanctions can turn antisocial."],
        "setting": "Shared-resource circle",
        "objects": [
            {"kind":"group","label":"contributors","fact":"People fund a shared resource.","track":[[110,225],[165,218],[220,210],[270,205],[270,205],[270,205]],"from":0},
            {"kind":"pot","label":"shared pot","fact":"Public-goods games model cooperation.","track":[[320,215],[320,215],[320,215],[320,215],[320,215],[320,215]],"from":0},
            {"kind":"stranger","label":"free-rider","fact":"Some participants contribute less.","track":[[560,230],[520,222],[480,214],[440,206],[410,200],[410,200]],"from":1},
            {"kind":"token","label":"costly sanction","fact":"Punishment often costs punishers.","track":[[160,145],[220,150],[280,158],[340,168],[400,180],[440,192]],"from":2},
            {"kind":"monitor","label":"elected monitor","fact":"Legitimate monitors gain compliance.","track":[[575,105],[525,115],[475,128],[425,142],[380,160],[350,178]],"from":3},
            {"kind":"warning","label":"antisocial risk","fact":"High contributors can face punishment.","track":[[320,92],[320,92],[320,92],[370,102],[420,115],[470,130]],"from":4},
        ],
    },
]
