import json, pathlib, html
p=pathlib.Path(__file__).resolve().parent
d=json.loads((p/'lesson.json').read_text())
template='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Money and evidence — viewer</title><style>
body{margin:0;background:#272735;color:#f0e5cc;font:17px system-ui,sans-serif} main{max-width:1100px;margin:auto;padding:20px}a{color:#ffcb70}button,input{font:inherit}button{background:#f0e5cc;color:#272735;border:0;padding:8px 13px;margin:3px;cursor:pointer}button:focus-visible,a:focus-visible{outline:3px solid #dda644} .screen{position:relative;background:#171721}video{width:100%;display:block}.hotspot{position:absolute;width:42px;height:42px;background:rgba(221,166,68,.85);border:2px solid #272735;border-radius:50%;transform:translate(-50%,-50%);font-size:13px;font-weight:bold}.hotspot:hover{background:#fff}.controls{display:flex;align-items:center;flex-wrap:wrap;gap:7px;margin:10px 0}input[type=range]{flex:1;min-width:170px}article{background:#363644;padding:18px;margin:16px 0}h1,h2{line-height:1.2} .sr{position:absolute;left:-9999px}body.reduced video,body.reduced .hotspot{display:none}body.reduced .screen{display:none}body.reduced .chapters{display:block}.chapters{display:none}.sources li{margin:7px 0}
</style><main><h1>Money and evidence</h1><p>Six investigations. This visual is a prototype. Motion review failed. Use the full text below.</p><label><input id="reduced" type="checkbox"> Reduced motion and text</label><div class="screen"><video id="video" src="history-investigation.mp4" preload="metadata" playsinline aria-label="Silent visual prototype"></video><div id="hotspots"></div></div><div class="controls"><button id="play">Play / pause</button><button id="back">−1 second</button><button id="step">+1 frame</button><button id="replay">Replay</button><input id="scrub" type="range" min="0" max="180" step="0.04" value="0" aria-label="Scene scrubber"><span id="time">0:00</span></div><article id="fact" aria-live="polite">Choose a paper object.</article><div class="chapters" id="chapters"></div><div id="full"></div></main><script id="lesson" type="application/json">__DATA__</script><script>
const D=JSON.parse(document.getElementById('lesson').textContent), V=document.getElementById('video'), R=document.getElementById('scrub'), T=document.getElementById('time'), H=document.getElementById('hotspots'), F=document.getElementById('fact');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const links=s=>'<ul class="sources">'+s.map(([t,u])=>'<li><a href="'+esc(u)+'" target="_blank" rel="noopener noreferrer">'+esc(t)+'</a></li>').join('')+'</ul>';
function update(){const t=V.currentTime||0, i=Math.min(5,Math.floor(t/30)), local=t-i*30, s=D.scenes[i];R.value=t;T.textContent=Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0');H.innerHTML='';s.objects.forEach((o,j)=>{const k=Math.min(4,Math.floor(local/6)),a=o.points[k],b=o.points[k+1],q=(local%6)/6,e=q*q*(3-2*q),x=a[0]+(b[0]-a[0])*e,y=a[1]+(b[1]-a[1])*e;let btn=document.createElement('button');btn.className='hotspot';btn.type='button';btn.style.left=(x/640*100)+'%';btn.style.top=(y/360*100)+'%';btn.textContent=j+1;btn.setAttribute('aria-label',o.label);btn.onclick=()=>F.innerHTML='<strong>'+esc(o.label)+'</strong><p>'+esc(s.summary)+'</p>'+links(s.sources);H.append(btn)});}
V.addEventListener('timeupdate',update);V.addEventListener('loadedmetadata',update);R.oninput=()=>{V.currentTime=+R.value;update()};document.getElementById('play').onclick=()=>V.paused?V.play():V.pause();document.getElementById('back').onclick=()=>{V.pause();V.currentTime=Math.max(0,V.currentTime-1)};document.getElementById('step').onclick=()=>{V.pause();V.currentTime=Math.min(180,V.currentTime+1/25)};document.getElementById('replay').onclick=()=>{V.currentTime=0;V.play()};document.getElementById('reduced').onchange=e=>{document.body.classList.toggle('reduced',e.target.checked);V.pause()};
document.getElementById('chapters').innerHTML=D.cards.map((c,i)=>'<article><h2>'+esc(c.title)+'</h2><p>'+esc(c.body)+'</p>'+links(c.sources)+'</article>').join('');document.getElementById('full').innerHTML='<h2>Full source cards</h2>'+D.cards.map((c,i)=>'<article><h3>'+esc(c.title)+'</h3><p>'+esc(c.body)+'</p>'+links(c.sources)+'</article>').join('');update();
</script></html>'''
(p/'lesson-viewer.html').write_text(template.replace('__DATA__',json.dumps(d,ensure_ascii=False).replace('</','<\\/')))
